### ISSUE TITLE
Correct naming in README.md

### ISSUE THREAD

**Issue by lusu007** [kryonitelabs/kryo-server-discovery#4]
**Describe the bug**
The README.md names this project `server-discovery` but its named `kryo-server-discovery`

**Expected behavior**
The title in the README.md should be `kryo-server-discovery`

**Comment by rohinish404** [comment]
i want to know regarding this issue that only the readme title needs to be changed, right?

**Comment by rohinish404** [comment]
i have created a pull request for the above issue. Please consider it..

**Comment by lusu007** [comment]
> i want to know regarding this issue that only the readme title needs to be changed, right?
You are spot on! We forgot to change the title in the README whilst renaming the project.
